# Generated by Django 5.1.3 on 2025-10-18 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='file',
            field=models.FileField(blank=True, upload_to='contact-docs/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'txt', 'docx'])]),
        ),
    ]
